// Power Query M snippets for cleaning & merging in Power BI
// 1. orders.csv: parse dates and types
let
    Source = Csv.Document(File.Contents("orders.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    ChangedTypes = Table.TransformColumnTypes(Promoted, {
        {"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"ProductID", type text},
        {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"Discount", type number}, {"Sales", type number},
        {"Cost", type number}, {"Profit", type number}, {"OrderPriority", type text}
    })
in
    ChangedTypes

// 2. Merge products & customers
let
    Orders = /* paste orders query */,
    Products = Csv.Document(File.Contents("products.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    ProductsPromoted = Table.PromoteHeaders(Products, [PromoteAllScalars=true]),
    Merged = Table.NestedJoin(Orders,{"ProductID"},ProductsPromoted,{"ProductID"},"Product",JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Merged, "Product", {"ProductName","Category","UnitPrice"}, {"ProductName","Category","UnitPrice"})
in
    Expanded
